### ISSUE TITLE
"Mapping" -> "Transformation"

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/cellfie-plugin#19]
The UI uses the word "Mapping" in various places, but "Transformation" is perhaps a better word. 

e.g.

"Mapping rules" ->  "Transformation rules"

"Translation" is also more inline with existing vocabulary, i.e. "Extract, Transform and Load (ETL)".

**Comment by johardi** [comment]
@csnyulas Any comment?

**Comment by csnyulas** [comment]
This is a delicate issue.

I know that "Mapping" is an overloaded term, but Cellfie is a Protege 5 plugin that provides a user friendly interface for the MappingMaster functionality in Protege. I.e. the engine underlying Cellfie is MappingMaster, which was developed and is maintained as a separate project (https://github.com/protegeproject/mapping-master). MappingMaster is extensively documented, including on wikis, mailing list archives, and several papers, and these sources always uses the "mapping expression" term to refer to the mappings. It is also natural that MappingMaster uses mapping expressions to describe the transformations.

So, although I agree that maybe "Transformation rules" would be a somewhat better or more accurate term, I feel that "Mapping rules" is definitely not wrong, or misleading, and maybe for the sake of the "backwards compatibility" with all the documentation I would just keep it as "Mapping rules". However, I would like to wait until @martinjoconnor returns from vacation to see what he thinks about this. That's why I did not jump right away to comment on this issue.

**Comment by martinjoconnor** [comment]
Don't really have a problem with the word 'transformation'. The mapping-master project README and wiki page use the word 'transform' in their opening sentences. 'Mapping' is a severely overloaded term so de-emphasizing it might not be a bad thing.

**Comment by csnyulas** [comment]
Sounds good.. Let's rename it to "Transformation rules" then.

**Comment by johardi** [comment]
Implemented at https://github.com/protegeproject/cellfie-plugin/commit/722afc6e3c2294fa607d77d33cc748694f298a2b

**Comment by johardi** [comment]
Fix at https://github.com/protegeproject/cellfie-plugin/commit/56bb43d9d26a9a67fd934f16b1a8d4acbf80e2bc, https://github.com/protegeproject/cellfie-plugin/commit/14b96ff3e05127ffac31bbaf9a0065314b921c96 and https://github.com/protegeproject/mapping-master/commit/9599faf9e6f7035781b074b887fd95f9c873ad38
