### ISSUE TITLE
Ordering bug between class assertion axiom and property assertion axiom

### ISSUE THREAD

**Issue by johardi** [protegeproject/cellfie-plugin#48]
This simple assertion rule below will throw a parsing exception:

```
Individual: @A*(mm:uuidEncode)
   Types: NutritionalInformation
   Facts: productName @A*,
          hasTotalFat @B*(xsd:decimal)
```

but not this:

```
Individual: @A*(mm:uuidEncode)
   Facts: productName @A*,
          hasTotalFat @B*(xsd:decimal)
   Types: NutritionalInformation
```

Notice the ordering between class assertion (Types) and property assertions (Facts).

**Comment by martinjoconnor** [comment]
This is the correct behaviour because those are likely two different references. 

@A_(mm:uuidEncode) is not the same as @A_ (even at the same cell location) - unless the default global rdf:ID encoding is mm:uuidEncode.

A reference is conceptually a pair consisting of a location and a set of reference directives, be they implicit or explicit. This implicit directive set is filled from the global default set. Two references are equal if they resolve to the same location _and_ ALL their directives are the same. 

An example could be reference 

```
@B*(ObjectProperty)
```

expanded to 

```
B4, {ObjectProperty rdfs:Label mm:ErrorIfEmptyLocation ...}
```

for row 4.

So if one of the above expressions were rewritten:

```
Individual: @A*(mm:uuidEncode)
   Type: NutritionalInformation
   Facts: productName @A*(mm:uuidEncode),
          hasTotalFat @B*(xsd:decimal)
```

then both @A\* references would resolve to the same thing. Or, if the default rdf:ID encoding is mm:uuidEncode then one or both of the explicit directives could be omitted and the references would be equal and also resolve to the same thing.

There is an internal map in MM that ensures this behaviour. It might be worth checking this and writing a test to ensure that it is true.

Global defaults can help ensure concision. In this case a default like:

```
mm:defaultRDFIDEncoding=mm:uuidEncode
```

would ensure that all references would use UIID encoding when creating rdf:IDs and that this directive would not have to be explicitly specified.

**Comment by johardi** [comment]
Hi Martin, thanks for the comment. But the real issue here is not about the reference resolution but more about the syntax parsing. The parser should not care about the ordering between Types and Facts. So either the two of my examples above shouldn't throw any exception.

**Comment by matthewhorridge** [comment]
Just a side point here, the Manchester Syntax uses `Types` not `Type`.  I'm just brining this up - not knowing whether this is a bug or not.

**Comment by johardi** [comment]
Sorry it was a typo. MM uses "Types"
I fixed my original post.

**Comment by johardi** [comment]
https://github.com/protegeproject/mapping-master/blob/master/src/main/jjtree/MappingMasterParser.jjt#L619-L624 shows such ordering bug

**Comment by csnyulas** [comment]
How about changing:

```
  <INDIVIDUAL> owl_named_individual(defaultIndividualValueEncoding) 
  ( <FACTS> fact_list() )?
  ( <TYPES> types(OWL_CLASS) )?
  ( <ANNOTATIONS> annotation_fact_list() )?
  ( owl_same_as() )?
  ( owl_different_from() )?
```

with 

```
  <INDIVIDUAL> owl_named_individual(defaultIndividualValueEncoding) 
  (
    ( <FACTS> fact_list() ) |
    ( <TYPES> types(OWL_CLASS) ) |
    ( <ANNOTATIONS> annotation_fact_list() ) |
    ( owl_same_as() ) |
    ( owl_different_from() ) |
  )*
```

**Comment by martinjoconnor** [comment]
Sorry - misunderstood the original post (though the test I mentioned in the response would be a good idea).

Yes - the above parser modification makes sense. Not sure why I did it the way I did. The proposed approach will will allow multiple sub-clauses of the same type (for example, several Facts: clauses) so check the Manchester Syntax to ensure that this is valid.

**Comment by martinjoconnor** [comment]
Also, make sure that the rendering engine can handle the multiple sub-clauses of the same type.

**Comment by johardi** [comment]
Fix via https://github.com/protegeproject/mapping-master/commit/8c9a25be8c9e22c7ffdf482b6a386158bd673b2e
