### ISSUE TITLE
Linking individuals

### ISSUE THREAD

**Issue by lhachin** [protegeproject/cellfie-plugin#70]
It's the first time for me using protégé and cellfie and I've been having some difficulties with my annotation property. 
As I did directly on protege before, an individual was linked with an annotation property to another individual through the entity IRI tab.
I've been trying to create a rule that would give me the same results without success. It is either error or string text.
After the tutorials and different things I've been reading I wanted to write :

Individual: @A*
Annotations:   rdfs:seeAlso @B*(mm:IRI)

In column B, there would be some of the individual already created with the exact same ortograph.
However it doesn't work and I'm not sure why.

This what I have
![cellfie](https://cloud.githubusercontent.com/assets/21197685/17893626/a63152c0-6946-11e6-81f4-19e6b735a31e.PNG)

And this is what I would like to have 
![protege](https://cloud.githubusercontent.com/assets/21197685/17893625/a62cb300-6946-11e6-9f86-85f288b49140.PNG)

I hope I'm clear, does anyone knows if it's possible?
Thanks in advance,

**Comment by martinjoconnor** [comment]
This seemed to work for me. See below.

![screen shot 2016-08-23 at 8 54 49 am](https://cloud.githubusercontent.com/assets/1731323/17899220/671d13b2-690f-11e6-88e6-325e9d597209.png)

**Comment by csnyulas** [comment]
As @martinjoconnor said, this should work. 
Maybe you can share with us your ontology, spreadsheet and rules files with us, @lhachin, so that we can take a closer look.

**Comment by lhachin** [comment]
Thank for your quick reply,
I managed to do it like in your exemple :  

![test](https://cloud.githubusercontent.com/assets/21197685/17922461/5f17c358-69df-11e6-9ee7-130d5ccd3b2f.PNG)

And I got : 

![test2](https://cloud.githubusercontent.com/assets/21197685/17922466/6eeac078-69df-11e6-9e73-edfee41b6b59.PNG)

However I would like my annotation to be a direct link to another individual. I used to do it like this on Protege : 

![test3](https://cloud.githubusercontent.com/assets/21197685/17922484/8c50ff92-69df-11e6-84c2-b429ec3ceb49.PNG)

So in the end I could get a direct link:

![test4](https://cloud.githubusercontent.com/assets/21197685/17922813/3984a000-69e1-11e6-8ea7-3356b031a39d.PNG)

(In this exemple I would like to link the skill Excel to Office, and to state Office as the most important skill for Microsoft. 
In the end, I am creating a skill ontology. I need to be able to link different skills between them so that they can be scored.)

**Comment by lhachin** [comment]
The 3 test files : 
[test.zip](https://github.com/protegeproject/cellfie-plugin/files/434267/test.zip)

**Comment by johardi** [comment]
There are 3 types of value for filling an annotation from the [OWL 2 specification](https://www.w3.org/TR/owl2-syntax/#Annotations):
1. a typed literal,
2. an anonymous individual, or 
3. an IRI.

Notice that the spec doesn't an entity (e.g., a named individual) as a valid value. So if you'd like to use an IRI as the annotation value (by using mm:IRI) and used it as an identifier for linking between entities then you should provide the correct IRI in the spreadsheet.

Technically speaking, Cellfie/MappingMaster won't do any further treatment for the input labels (like appending a default prefix) but instead it will just take the label value (e.g., Office or Microsoft) as it is and transform it as an IRI object, such as:

```
Excel rdfs:seeAlso <Office>
Microsoft rdfs:seeAlso <Office>
Office rdfs:seeAlso <Microsoft>
```

Try to re-execute the transformation rules with the new spreadsheet and ontology in the attachment to get my explanation --> [Archive.zip](https://github.com/protegeproject/cellfie-plugin/files/437743/Archive.zip).

Having said that, I understand that it is much more convenient to work with labels rather than IRI identifiers in the spreadsheet. As a solution I can make an extension in the code such that it will look for an existing entity in the ontology, fetch the IRI identifier and reuse it.

**Comment by csnyulas** [comment]
@johardi if you do such an extension, do we need a new `mm:` directive for it? Or in case of the `mm:IRI` directive you would check if the value is a well formed IRI, and if not you would try to identify the corresponding IRI by the label?

**Comment by martinjoconnor** [comment]
I think creating an IRI by resolving an entity through its label and then using that entity's IRI might be going too far for this directive. 

I agree that it might be worthwhile determining if the referenced cell contains a well formed IRI for <tt>mm:IRI</tt> directives and automatically constructing one if not - but I think it should be constructed by prepending the base ontology namespace to it.

For example, if the base namespace of an ontology is <tt>https://example.com#</tt> and the contents of cell A3 used in reference <tt>@A3(mm:IRI)</tt> is <tt>Fred</tt> then the IRI <tt>https://example.com#Fred</tt> can be constructed. If the cell contains a valid IRI then it can be used directly. 

I think using the cell's value as a label to resolve an entity and then using the IRI of that resolved entity is going way too far for the <tt>mm:IRI</tt> directive since it is designed to work with IRIs, not OWL entities. 

Perhaps a new directive could be introduced with this behaviour (<tt>mm:ResolveIRIViaLabel</tt>?) - though it does seem rather specialized to me.

**Comment by johardi** [comment]
I was thinking the solution like what @csnyulas has mentioned; to have an extra check if the label can represent an existing entity.

Protege uses a much the same approach in its annotation editor dialog. The dialog offers you two ways to have an IRI value: (1) using the "Entity IRI" or (2) using the "IRI editor". In the "Entity IRI" tab, the user can select an IRI from an entity label. We could use this same approach in Cellfie for consistency.

![screen shot 2016-08-26 at 9 37 43 am](https://cloud.githubusercontent.com/assets/5062950/18012977/cba89532-6b70-11e6-9ab7-c6979688245e.png)

**Comment by csnyulas** [comment]
I agree with @martinjoconnor, and @johardi examples are really useful for clarifying the use case. I think a new directive, such as `mm:EntityIRI`, with the smart behaviour that includes both the one suggested by @martinjoconnor and by @johardi would solve all the issues. Right?

**Comment by martinjoconnor** [comment]
I second. I also like the name <tt>mm:EntityIRI</tt>.

**Comment by johardi** [comment]
OK I'll put this into 2.1.0 milestone

**Comment by lhachin** [comment]
Thank you for your help ! :)
I'll be trying @johardi  solution and waiting for the new version!

**Comment by johardi** [comment]
Fixed via https://github.com/protegeproject/mapping-master/commit/cde136508ed5d0edc96d73fcdddaa1bdcfed710b

**Comment by lhachin** [comment]
Hello,
I've been trying with the new version of Cellfie to do the linking between individuals with mm:IRI. It does the same thing as before.
And when I try with mm:EntityIRI, the annotation doesn't appear in Protégé.
Am I doing it wrong ?
Thanks for your time !

[test.zip](https://github.com/protegeproject/cellfie-plugin/files/542039/test.zip)

**Comment by johardi** [comment]
The `mm:EntityIRI` works by reusing the IRI of the existing entities in the ontology. It means that when you want to apply this rule below, the Individuals from column C must be present already in the ontology.

```
Individual: @B*
Annotations: rdfs:seeAlso @C* (mm:EntityIRI)
```

In your case, you need to run Cellfie in two subsequent steps. First, generate the class and individual declaration axioms using the first two rules and then add to the current ontology. Second, create the annotation assertion axioms (the rule above) and add to the same ontology. In this way, you should be able to get the linking Individuals.

**Comment by lhachin** [comment]
Thanks it's working :)

**Comment by amanEdris** [comment]
@lhachin I was trying the  example you attached. When i run the rules my result has somehow a different URI. It appends on  foaf:Agent. I was wondering why that might be?
[
![Screen Shot 2020-11-14 at 8 28 41 PM](https://user-images.githubusercontent.com/20907174/103147419-e558c080-4765-11eb-966a-513b1b577d7a.png)
](url)
