### ISSUE TITLE
Simpler auto-generated names

### ISSUE THREAD

**Issue by johardi** [protegeproject/cellfie-plugin#8]
Instead of giving an auto-generated name like SheetName_A2_43894893493843, would it be possible to start from 1 so that we get names like SheetName_A2_1.

**Comment by johardi** [comment]
What about using the first 7 characters SHA1 hash? Implementation at https://github.com/protegeproject/mapping-master/commit/9aef6df09e92cccb1dd81616845963c7abbecc4b

**Comment by martinjoconnor** [comment]
1-indexed would be ideal (Protege 3 API provided this) but if the underlying API does not make this easy then the above shorter solution would be better (assuming it guarantees uniqueness).

**Comment by johardi** [comment]
Just an observation: do we really need extra string after 'sheet name' and cell location? Both combination provides a unique identifier already, e.g., SheetOneA1, ProductListB32

I did a reimplementation to use camel case instead of snake case and remove the extra SHA1 string https://github.com/protegeproject/mapping-master/commit/ed14961450f00806bb9e7917c38ee861e56bd16a

Hopefully this is a right thing to do.

**Comment by martinjoconnor** [comment]
The problem is that a set of expressions could use the same cell for multiple reasons. 

For example, if we had the following two expressions, one of which creates a class and another of which creates and individual

Class: @A1 SubClassOf: Horse
Individual:  @A1 Types: Dog

then we would have a class and individual with the same name (which would cause an error). 

The above would not be common, but is possible.

One option would be to append, say, _C, _I, _OP, _DP, _AP to the sheet/location name depending on the type of OWL entity. This would fix the collision problem.

**Comment by csnyulas** [comment]
The example given by @martinjoconnor should not cause an error in OWL 2. It should just cause punning, which it appears to me that it is exactly what the user wants. Punned individuals/classes/properties are totally different entities from the point of view of the reasoner, despite the fact that they share their name.

**Comment by martinjoconnor** [comment]
Cool. Did not realize that. So the shorter names with the sheet and location names should suffice.
